---
title: ""
knit: (function(input_file, encoding) {
  out_dir <- '../docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'research.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---

<center> <h1>Research Experience</h1> </center>

</div>
<div style="margin-bottom:40px;">
</div>


## Publications & Preprints

* __Xu, Y.__, Düker, M. C., \& Matteson, D. S. (2023). _Testing Simultaneous Diagonalizability_. _Journal of the American Statistical Association_, 119 (546), 1513-1525. [__doi: 10.1080/01621459.2023.2202435__](https://doi.org/10.1080/01621459.2023.2202435).

* __Xu, Y.__, Thomas, A. M., Crozier, P. A., \& Matteson, D. S. (2025). _Dynamic Atomic Column Detection in Transmission Electron Microscopy Videos via Ridge Estimation_. _IEEE Transactions on Image Processing_, 34, 1588-1601. [__doi:10.1109/TIP.2025.3543138__](https://doi.org/10.1109/tip.2025.3543138).

* Manzorro, R., __Xu, Y.__, Vincent, J., Rivera, R., Matteson, D., \& Crozier, P. (2022). _Exploring Blob Detection to Determine Atomic Column Positions and Intensities in Time-Resolved TEM Images with Ultra-Low Signal-to-Noise_. _Microscopy and Microanalysis_, 28 (6), 1917-1930. [__doi:10.1017/S1431927622000356__](https://doi.org/10.1017/S1431927622000356).

* Thomas, A. M., Crozier, P. A., __Xu, Y.__, \& Matteson, D. S. (2023). _Feature Detection and Hypothesis Testing for Extremely Noisy Nanoparticle Images using Topological Data Analysis_. _Techonometrics_, 65 (4), 590-603. [__doi: 10.1080/00401706.2023.2203744__](https://doi.org/10.1080/00401706.2023.2203744).

* Goolsby, C., Losey, J., __Xu, Y.__, Düker, M. C., Sherman, M. G., Matteson, D. S., \& Moradi, M. (2021). _Addressing the Embeddability Problem in Transition Rate Estimation_. _Journal of Physical Chemistry A_, 127 (27), 5745-5759. [__doi: 10.1021/acs.jpca.3c01367__](https://doi.org/10.1021/acs.jpca.3c01367).

* Calabro, C., Sadhu R., __Xu, Y.__, Aprea, M., Guarino, C., \& Cazer C. L. (2024). _Longitudinal Antimicrobial Susceptibility Trends of Canine Staphylococcus Pseudintermedius_. _Preventive Veterinary Medicine_, 226, 106170. [__doi:10.1016/j.prevetmed.2024.106170__](https://doi.org/10.1016/j.prevetmed.2024.106170).

* Thomas, A. M., Lin, A. C., Deng, G., __Xu, Y.__, Ranvier, G. F., Taye, A., Matteson, D. S., \& Lee, D. (2024). _A Proof-of-Concept Investigation into Predicting Follicular Carcinoma on Ultrasound Using Topological Data Analysis and Radiomics._ _Imaging_, 2025. [__doi:10.1556/1647.2025.00256__](https://doi.org/10.1556/1647.2025.00256).



</div>
<div style="margin-bottom:60px;">
</div>

## Presentations

#### Learning of Multi-level Granger Causal Connectivity

* Jun 2025. The 38th New England Statistics Symposium (NESS), Advances in Modeling and Methodology for Multiple-Subject Time Series, Invited Session. New Haven, CT.

#### Joint Learning of Panel VAR models with Low Rank and Sparse Structure

* Aug 2025. Joint Statistical Meeting (JSM), Advances in High-Dimensional Time Series: Causality, Learning, and Dimension Reduction, Invited Session. Nashville, TN.

* Jan 2025. Department Seminar in the Department of Statistics at the University of California, Santa Cruz, CA.

* Nov 2024. The Conference on Statistical Learning and Data Science (SLDS), Analysis of High Dimensional Data with Complex Structure Section, Invited Session. Newport Beach, CA.

* Aug 2024. Joint Statistical Meeting (JSM), Business and Economic Statistics Section, Poster Session. Portland, OR.

#### Dynamic Atomic Column Detection in Transmission Electron Microscopy Videos via Ridge Estimation

* May 2023. The Statistical Methods in Imaging Conference 2023, Contributed Session. *__First-Place Winner of Student Paper Competition Case Studies and Applications track__*. Minneapolis, MN.

#### Non-parametric ridge recovery of TEM image series given temporal parameterization

* Oct 2022. 2022 INFORMS Annual Meeting, Science-Integrated Statistical Learning Section, Contributed Technical Session. Indianapolis, IN.

* Nov 2022. 2022 IEEE Western New York Image and Signal Processing Workshop (WNYISPW), Poster Session, *__Best Student Poster Award__*. (Hybrid) Rochester, NY.

#### Recording atomic column positions and intensities via Blob Detection in noise-degraded TEM frames

* Apr 2021. UPSTAT 2021 Conference, Contributed Parallel Session, *__Bronze Medal Presenter__*. (Virtual) Rochester, NY.

* Feb 2022. The 37th SIDIM, Data Science in Science Minisymposia, Contributed Parallel Session. (Virtual) Puerto Rico.

#### Testing Simultaneous Diagonalizabiliy

* May 2023. Conference on Advances in Time Series Analysis, Contributed Speedy Session. Chicago, IL.

* July 2019. Joint Statistical Meeting (JSM), Business and Economic Statistics Section, Contributed Speed Session. Denver, CO.

* Sept 2019. Cornell Celebration of Statistics and Data Science, Poster Session. Ithaca, NY.

</div>
<div style="margin-bottom:60px;">
</div>


## Collaborations

* [__HDR Catalyst Project__](https://www.nsf.gov/awardsearch/showAward?AWD_ID=1940124&HistoricalAwards=false) | Nov 2019 - Present | Ithaca, NY\
Collaborate with groups of:
    * [__Prof. Roberto Rivera__](https://scholar.google.com/citations?user=0HEAaC4AAAAJ&hl=en): propose and adapt hidden Markov models to dynamically cluster nanoparticle atomic structural configurations.

    * [__Prof. Peter A. Crozier__](https://crozier.engineering.asu.edu/people/peter-a-crozier/): adapt blob detection algorithm to extract locations and intensities of atomic columns.

    * [__Prof. Mahmoud Moradi__](https://bslgroup.hosted.uark.edu/members.shtml): refine the estimators of Markov chain transition rate matrices from transition probability matrices.


* Heart Failure Project | Dec 2021 - Present | Ithaca, NY\
Collaborate with [New York-Presbyterian (NYP) Hospital](https://www.nyp.org/) to conduct patients' heart failure inference from Electrocardiograms (ECG) data with other hospital-visit records.


* Thyroid Cancer Project | Dec 2022 - Present | Ithaca, NY\
Collaborate with [Denise Lee, MD](https://profiles.mountsinai.org/denise-t-lee) to predict Differentiated Thyroid Cancer (DTC) recurrence.
